title: APRS via LoRa
title_separator: "-"
subtitle: "Send your position data via LoRa!"
description: >-
  APRS via LoRa: the new communication format for every ham who want's to have ultra low power APRS on the go for less money.
url: https://www.lora-aprs.info
github_username: lora-aprs
minimal_mistakes_skin: dirt
search: false

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 10
paginate_path: /blog/page:num/
timezone: Europe/Vienna
logo: "/assets/images/logo_small.png"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lora-aprs"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  - scope:
      path: "docs"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
